### ISSUE TITLE
Fluid Equilibrium Issue

### ISSUE THREAD

**Issue by Erabior** [LolHens/mc-fluid-physics#14]
I'm not sure what is causing this, but the fluid is not leveling out properly. for instance, if you add a drain in the bottom of a LARGE body of water. The water will develop a funnel but when sealed the funnel will not level out with surrounding fluid. Likewise, if for instance, water flows through a cavern into a ravine, water will not level out but rather travel 8 blocks and then stop. I'm not sure if this whole issue is due to the bug mentioned in the mod description that causes water to stop flowing so yeah.

**Comment by LolHens** [comment]
Yes this is the limitation mentioned in the readme. Because I still rely on the vanilla fluid physics for a lot of things (on purpose) there are a few edge cases where block updates are not properly propagated. This is an issue I've been scratching my head on for a few years now. Maybe I'll come up with a solution in the future.

**Comment by Erabior** [comment]
Yeah I was talking about how they want equal out at all. If it's any help the source code for finite fluids (realistic fluid physics) for 1.7.10 has been made available by the mod author. I tried to update it to the latest version of Minecraft a few times but found that it's extremely difficult unless you know a lot about both versions of the forge api in order to properly change any references to it. So if you're trying to Make a new physics engine for water specifically that might be the best place to check.

**Comment by LolHens** [comment]
This mod doesn't implement real water physics on purpose because it would break many established game mechanics. You might find a mod that does what you are looking for here: https://github.com/LolHens/mc-fluid-physics#similar-mods
