### ISSUE TITLE
Cant connect to 1.16 server with this mod

### ISSUE THREAD

**Issue by Bradovman** [LolHens/mc-fluid-physics#21]
When i try to connect to a server with fluid physics installed it shows this error message
```
Registry remapping failed: Received ID map for Minecraft:block contains IDs unknown to the receiver!
-fluidphysics: spring
```
My config Looks like this:

```
{
  "fluidWhitelist": [
    "minecraft:water",
    "minecraft:lava"
  ],
  "findSourceMaxIterations": 255,
  "findSourceMaxCheckedBlocks": 4095,
  "biomeDependentFluidInfinity": false,
  "flowOverSources": true,
  "debugFluidState": false,
  "spring": {
    "block": "minecraft:mossy_cobblestone",
    "updateBlocksInWorld": false,
    "allowInfiniteWater": true
  },
  "rainRefill": {
    "probability": 0.2,
    "fluidWhitelist": [
      "minecraft:water"
    ],
    "biomeDependent": true
  }
}
```

**Comment by LolHens** [comment]
Hi, you are probably trying to connect with a vanilla client which is wha you are using mossy cobble as spring block.
Have you generated the world before changing this config option? If so you probably already have the spring block from this mod in your worls. You can use the "updateBlocksInWorld" config option to automatically replace all existing spring blocks with mossy cobblestone. Just keep in mind that you cannot go the other direction from mossy cobblestone back to spring blocks or at least not automatically.

**Comment by LolHens** [comment]
@Bradovman did you get a chance to try this yet?

**Comment by Bradovman** [comment]
It worked, thanks a lot. Sorry i forgot to reply.
