### ISSUE TITLE
Waterlogging feature

### ISSUE THREAD

**Issue by xtrial** [LolHens/mc-fluid-physics#23]
Please add support for waterlogging

**Comment by LolHens** [comment]
What do you mean? All the waterlogging things that can be done in vanilla should also work with this mod. Water can even flow through trapdoors. Do you have an example of something that should be possible?

**Comment by xtrial** [comment]
Sorry for not detailed enough,
Looks like quark's speleothem is not waterlogged when fluid flows thru
them. I will attach screenshot later.

**Comment by xtrial** [comment]
Sorry, my mistake
I thought this was a missing feature in this mod but i'm so wrong. lol
I just played 1.16.5 and assumed that flowing water can waterlog a waterloggable block, but it's not even a feature yet in vanilla minecraft.

**Comment by LolHens** [comment]
haha ok well maybe I can do something about these things in the future.
