### ISSUE TITLE
Crash when load the game [Minecraft 1.17]

### ISSUE THREAD

**Issue by narisuzu** [LolHens/mc-fluid-physics#58]
Crash report:
https://gist.githubusercontent.com/natanfudge/f6eea1e91c2eb8bcb2dc4095458a11c4/raw/77b4c6a9406fa28cc68f44a0724f732e614b0f09/crash.txt

**Comment by JamesTheMaker** [comment]
I'm experiencing this problem as well. It doesn't appear to be any kind of conflict, because I attempted to load the mod by itself and it still doesn't work.

**Comment by LolHens** [comment]
There was no 1.17 version until an hour ago. The previous releases were for the snapshot releases.
Could you try with the new 1.17.1 release?

**Comment by LolHens** [comment]
Please comment if you are still having issues.
