### ISSUE TITLE
[Suggestion] Better way to deal with oceans filling up slowly

### ISSUE THREAD

**Issue by someaddons** [LolHens/mc-fluid-physics#77]
At the moment when you have one part of the ocean higher than another, due to e.g. some worldgen letting a bunch of water flow ontop of the ocean water (ye you need flowing ontop of fluid sources enabled for that) then rain will over time with its refill creep up the ocean level slowly. 

What I'm suggesting is an option to have oceans/river/other water biomes to "swallow/void" a fluid source when flowing ontop of another which is at the worlds sea/water level(so you can still fill up a river to sea level, but not above). Then you can do stuff like draining water into rivers/oceans aswell

**Comment by LolHens** [comment]
Ah yes I've had this issue in the past on one of my maps. It was the reason I introduced the `/fluidphysics removelayers command`.
I really like the idea of oceans and rivers acting as a void or not being filled up higher than sea level.

**Comment by someaddons** [comment]
ye I think its the most elegant solution to the problem, since you'd view oceans/rivers as mostly infinite water pools due to their size anyways

**Comment by ncottrill** [comment]
Once the mod is updated to reflect this suggested ocean-river void mechanic, I believe there will need to be some way to manually "reset" the "sea level" for those flooded areas.

For example, in the biome that has been flooded, the water level is now about 15 blocks higher than the original "sea level". With the current algorithm and with the "rain" that attempts to "fix / heal" bodies of water, this increased 15 block height has become the lake's "new normal sea level." This is what is causing flooding. This is also why I foresee that we will need to have a command that will allow us to reset the "sea level." 

It could be that somewhere in the Minecraft worldgen code the value for the original "sea level" exists and your mod algorithm could get that value and use it. But, if not, we as players can usually see where the original level was. Then, with an appropriate command that this mod would create for us, we could see the Y value of the original level and input that value in order "fix" the "sea level" back to its original size.

**Comment by someaddons** [comment]
sea level is a global world value defined on world creation, set its pre-set in stone and does not change. If the suggested change is added the water would stop advancing on the biomes in question like rivers/oceans

**Comment by LolHens** [comment]
yes the void mechanic will use this value. You can even "reset" the level in the current version using the `/fluidphysics removelayers` command mentioned above. It will remove any layers above your current y level (the command will ask you to confirm your choice so you can check the values again).

**Comment by ncottrill** [comment]
![image](https://user-images.githubusercontent.com/14022160/126436388-0337e150-50e5-48c6-adbf-e14334b54696.png)
This is the flooded "Crag Gardens" biome (flood is bleeding into the swamp area).

**Comment by ncottrill** [comment]
We have put the logs in to "block" the "source" water blocks and you can see that above the logs is a higher level than below the logs (pic above).

This is us trying to wall off parts of the flood and then soak up the water with sponges. The green in the background is the tops of trees that are flooded. 
![image](https://user-images.githubusercontent.com/14022160/126436625-1a7df3d7-b297-4ba5-8caf-06b07e597e47.png)

**Comment by ncottrill** [comment]
Could you give me an idea about when you could get this mod updated with the algorithm that voids water above "sea level"? And, will it fix this for us? This is a lot of work to prevent flooding our base.

**Comment by someaddons** [comment]
Little bump, would be nice if we could get this feature I think it'd perfectly round up the mods design overall

**Comment by LolHens** [comment]
implemented in v1.6.0

**Comment by someaddons** [comment]
nice :1st_place_medal:  gonna test it

**Comment by someaddons** [comment]
works nicely, closing this
